# Generated by Django 3.2.4 on 2021-06-21 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_alter_project_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='title',
        ),
    ]
