# Generated by Django 3.2.4 on 2021-06-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='author_note',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
