# Generated by Django 3.2.4 on 2021-06-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_experience_qualification_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
